let mock = [{id:1,species:"Helmeted guinea fowl",firstName:"Rafael",lastName:"Pasley",gender:"Male",gpa:2.57,image:"helmeted-guinea-fowl.jpg"},
{id:2,species:"Screamer, southern",firstName:"Chas",lastName:"Clynter",gender:"Male",gpa:2.09,image:"southern-screamer.jpg"},
{id:3,species:"Bent-toed gecko",firstName:"Charmian",lastName:"Sellens",gender:"Female",gpa:3.09,image:"bent-toed-gecko.jpg"},
{id:4,species:"Elephant, african",firstName:"Alley",lastName:"Key",gender:"Male",gpa:2.6,image:"african-elephant.jpg"},
{id:5,species:"South African hedgehog",firstName:"Hetti",lastName:"Nevett",gender:"Female",gpa:3.48,image:"south-african-hedgehog.jpg"},
{id:6,species:"Heron, boat-billed",firstName:"Amberly",lastName:"Ferreli",gender:"Female",gpa:2.17,image:"boat-billed-heron.jpg"},
{id:7,species:"American racer",firstName:"Moina",lastName:"Sergeaunt",gender:"Female",gpa:3.47,image:"american-racer.jpg"},
{id:8,species:"Oryx, fringe-eared",firstName:"Alexander",lastName:"Bodemeaid",gender:"Male",gpa:3.1,image:"fringe-eared-oryx.jpg"},
{id:9,species:"Guerza",firstName:"Nichols",lastName:"Ghilks",gender:"Male",gpa:3.85,image:"guerza.jpg"},
{id:10,species:"Porcupine, crested",firstName:"Sonnie",lastName:"Cunliffe",gender:"Male",gpa:2.36,image:"crested-porcupine.jpg"},
{id:11,species:"Possum, pygmy",firstName:"Giraud",lastName:"Corbett",gender:"Male",gpa:3.58,image:"pygmy-possum.jpg"},
{id:12,species:"Grey fox",firstName:"Yancy",lastName:"Pinock",gender:"Male",gpa:3.15,image:"grey-fox.jpg"},
{id:13,species:"Rhinoceros, black",firstName:"Jordanna",lastName:"Pennycord",gender:"Female",gpa:2.33,image:"black-rhinoceros.jpg"},
{id:14,species:"Mountain lion",firstName:"Philippe",lastName:"Camings",gender:"Female",gpa:3.82,image:"mountain-lion.jpg"},
{id:15,species:"Lion, california sea",firstName:"Armstrong",lastName:"Harby",gender:"Male",gpa:3.36,image:"california-sea-lion.jpg"},
{id:16,species:"Dolphin, bottle-nose",firstName:"Lida",lastName:"Van Zon",gender:"Female",gpa:3.29,image:"bottle-nose-dolphin.jpg"},
{id:17,species:"Sidewinder",firstName:"Mirella",lastName:"Rosendahl",gender:"Female",gpa:3.91,image:"sidewinder.jpg"},
{id:18,species:"White-mantled colobus",firstName:"Eldin",lastName:"Dupoy",gender:"Male",gpa:3.68,image:"white-mantled-colobus.jpg"},
{id:19,species:"Black spider monkey",firstName:"Leland",lastName:"Springham",gender:"Male",gpa:3.48,image:"black-spider-monkey.jpg"},
{id:20,species:"Caribou",firstName:"Cecilio",lastName:"Farfull",gender:"Male",gpa:2.15,image:"caribou.jpg"},
{id:21,species:"Kangaroo, brush-tailed rat",firstName:"Stace",lastName:"Boullen",gender:"Female",gpa:2.26,image:"brush-tailed-rat-kangaroo.jpg"},
{id:22,species:"Kingfisher, white-throated",firstName:"Ira",lastName:"Riordan",gender:"Female",gpa:2.78,image:"white-throated-kingfisher.jpg"},
{id:23,species:"Sandhill crane",firstName:"Eirena",lastName:"Biddlecombe",gender:"Female",gpa:3.58,image:"sandhill-crane.jpg"},
{id:24,species:"Asiatic jackal",firstName:"Cybill",lastName:"Long",gender:"Female",gpa:2.33,image:"asiatic-jackal.jpg"},
{id:25,species:"Chuckwalla",firstName:"Vinny",lastName:"Chaster",gender:"Female",gpa:2.52,image:"chuckwalla.jpg"},
{id:26,species:"Clark's nutcracker",firstName:"Marika",lastName:"Gumery",gender:"Female",gpa:3.71,image:"clarks-nutcracker.jpg"},
{id:27,species:"Flamingo, lesser",firstName:"Jamal",lastName:"Seel",gender:"Male",gpa:3.66,image:"lesser-flamingo.jpg"},
{id:28,species:"Mara",firstName:"Bruis",lastName:"Rustich",gender:"Male",gpa:2.2,image:"mara.jpg"},
{id:29,species:"Crab, red lava",firstName:"Danell",lastName:"Wyburn",gender:"Female",gpa:2.4,image:"red-lava-crab.jpg"},
{id:30,species:"Vulture, black",firstName:"Alfreda",lastName:"Darrach",gender:"Female",gpa:3.14,image:"black-vulture.jpg"},
{id:31,species:"Polar bear",firstName:"Munmro",lastName:"Kreutzer",gender:"Male",gpa:3.95,image:"polar-bear.jpg"},
{id:32,species:"Indian red admiral",firstName:"Jeffrey",lastName:"Dimitrescu",gender:"Male",gpa:2.78,image:"indian-red-admiral.jpg"},
{id:33,species:"Hawk, galapagos",firstName:"Sean",lastName:"Dowles",gender:"Male",gpa:3.48,image:"galapagos-hawk.jpg"},
{id:34,species:"Sage grouse",firstName:"Raphaela",lastName:"Badsey",gender:"Female",gpa:3.05,image:"sage-grouse.jpg"},
{id:35,species:"Hartebeest, coke's",firstName:"Brad",lastName:"Pointing",gender:"Male",gpa:2.25,image:"cokes-hartebeest.jpg"},
{id:36,species:"Hyena, spotted",firstName:"Maximilien",lastName:"Scoular",gender:"Male",gpa:2.75,image:"spotted-hyena.jpg"},
{id:37,species:"Tortoise, indian star",firstName:"Alyse",lastName:"Szymczyk",gender:"Female",gpa:2.85,image:"indian-star-tortoise.jpg"},
{id:38,species:"American bison",firstName:"Arley",lastName:"Eaden",gender:"Male",gpa:3.26,image:"american-bison.jpg"},
{id:39,species:"Bahama pintail",firstName:"Devi",lastName:"McTrusty",gender:"Female",gpa:3.61,image:"bahama-pintail.jpg"},
{id:40,species:"Nighthawk, common",firstName:"Freemon",lastName:"Whitebrook",gender:"Male",gpa:2.64,image:"common-nighthawk.jpg"},
{id:41,species:"Bird (unidentified)",firstName:"Joell",lastName:"Clarey",gender:"Female",gpa:2.07,image:"unidentified-bird.jpg"},
{id:42,species:"Lark, horned",firstName:"Ernie",lastName:"Dreamer",gender:"Male",gpa:3.26,image:"horned-lark.jpg"},
{id:43,species:"Bulbul, african red-eyed",firstName:"Farica",lastName:"Gilleon",gender:"Female",gpa:3.82,image:"african-red-eyed-bulbul.jpg"},
{id:44,species:"Skua, great",firstName:"Nertie",lastName:"Ellice",gender:"Female",gpa:2.29,image:"great-skua.jpg"},
{id:45,species:"South American puma",firstName:"Lindsay",lastName:"Krause",gender:"Male",gpa:2.81,image:"south-american-puma.jpg"},
{id:46,species:"Jaguar",firstName:"Jude",lastName:"de Castelain",gender:"Male",gpa:3.25,image:"jaguar.jpg"},
{id:47,species:"European red squirrel",firstName:"Sayre",lastName:"Kramer",gender:"Male",gpa:2.5,image:"european-red-squirrel.jpg"},
{id:48,species:"Agama lizard (unidentified)",firstName:"Aindrea",lastName:"Bernholt",gender:"Female",gpa:2.3,image:"unidentified-agama-lizard.jpg"},
{id:49,species:"Mongoose, eastern dwarf",firstName:"Vallie",lastName:"Cruddas",gender:"Female",gpa:3.69,image:"eastern-dwarf-mongoose.jpg"},
{id:50,species:"Eagle, long-crested hawk",firstName:"John",lastName:"Burgne",gender:"Male",gpa:2.25,image:"long-crested-hawk-eagle.jpg"}];

export default mock;